import ChatMessage from '../models/ChatMessage.js';

// @desc    Get chat messages
// @route   GET /api/chat/:hotelId?
// @access  Private
export const getMessages = async (req, res, next) => {
  try {
    const { hotelId } = req.params;
    let query = { user: req.user.id };

    if (hotelId) {
      query.hotel = hotelId;
    }

    const messages = await ChatMessage.find(query)
      .populate('hotel', 'name')
      .sort('createdAt')
      .limit(100);

    res.json({
      success: true,
      count: messages.length,
      data: messages,
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Send message
// @route   POST /api/chat
// @access  Private
export const sendMessage = async (req, res, next) => {
  try {
    const { hotel, booking, message, sender } = req.body;

    const chatMessage = await ChatMessage.create({
      user: req.user.id,
      hotel,
      booking,
      message,
      sender: sender || 'user',
    });

    const populatedMessage = await ChatMessage.findById(chatMessage._id)
      .populate('hotel', 'name');

    res.status(201).json({
      success: true,
      data: populatedMessage,
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get chat summary
// @route   GET /api/chat/summary/:bookingId
// @access  Private
export const getChatSummary = async (req, res, next) => {
  try {
    const messages = await ChatMessage.find({
      booking: req.params.bookingId,
      user: req.user.id,
    }).sort('createdAt');

    if (messages.length === 0) {
      return res.status(404).json({
        success: false,
        message: 'No messages found for this booking',
      });
    }

    // If summary already exists, return it
    const messageWithSummary = messages.find(m => m.summary);
    if (messageWithSummary) {
      return res.json({
        success: true,
        summary: messageWithSummary.summary,
      });
    }

    // Generate summary (will be done via AI service in actual implementation)
    const summary = 'Chat summary will be generated by AI service';

    res.json({
      success: true,
      summary,
    });
  } catch (error) {
    next(error);
  }
};

